### ISSUE TITLE
Illinois does have a gross income test for elderly_or_disabled.

### ISSUE THREAD

**Issue by benmolin** [18F/snap-js-api-prototype#34]
For the Gross Income Test, Illinois limit is 165% for households without elderly or disabled members and 200% with [(source)](https://www.dhs.state.il.us/page.aspx?item=30357).

Current code defaults to no states have a Gross Income Test for elderly_or_disabled households: [Gross Income Test](https://github.com/18F/snap-js-api-prototype/blob/main/src/tests/gross_income_test.js#L18)

```        

if (this.household_includes_elderly_or_disabled) {
       return {
                'name': 'Gross Income Test',
                'result': true,
                'explanation': [
                    'The first test we\'ll check for SNAP eligibility is the Gross Income Test.',
                    'Households with an elderly or disabled member do not need to meet the gross income test.'
                ],
                'sort_order': 2,
                'type': 'test',
            };
        }

```

To reproduce, use the [Illinois Snap Prescreener](https://github.com/18F/snap-js-prescreener-prototypes/blob/main/prescreeners/il.html) with a profile that has elderly_or_disabled = True and view the "why" output where it states they do not need to meet the gross income test.

**Suggested solution:**

First, add two more lines to state options:

1. gross_income_limit_factor_elderly_or_disabled, a number if the state has a separate gross income limit for elderly_or_disabled, null if not
2. has_gross_income_test_elderly_or_disabled, a boolean, whether the state has any gross income test for elderly_or_disabled

_IL_
```
            'gross_income_limit_factor': 1.65,
            'gross_income_limit_factor_elderly_or_disabled': 2.00,
            'has_gross_income_test_elderly_or_disabled': true,
```

_VA_
```
            'uses_bbce': false,
            'has_gross_income_test_elderly_or_disabled': false,
```

Then, make sure the new limit replaces the old limit in [snap-estimate.js](https://github.com/18F/snap-js-api-prototype/blob/main/src/snap_estimate.js#L99) when needed.

New code:

```

if (uses_bbce) {
    if ((state_options['gross_income_limit_factor_elderly_or_disabled'] != null) & (this.household_includes_elderly_or_disabled)) {
        this.gross_income_limit_factor = state_options['gross_income_limit_factor_elderly_or_disabled'];

    } else {
        this.gross_income_limit_factor = state_options['gross_income_limit_factor'];
    };
} else {
    this.gross_income_limit_factor = DEFAULT_GROSS_INCOME_LIMIT_FACTOR;
};


```

Finally, change the [Gross Income Test](https://github.com/18F/snap-js-api-prototype/blob/main/src/tests/gross_income_test.js#L18) to account for this.

```
if ((this.household_includes_elderly_or_disabled) & (this.has_gross_income_test_elderly_or_disabled == false)) {
    return {
        'name': 'Gross Income Test',
        'result': true,
        'explanation': [
            'The first test we\'ll check for SNAP eligibility is the Gross Income Test.',
            'Households with an elderly or disabled member do not need to meet the gross income test.'
        ],
        'sort_order': 2,
        'type': 'test',
    };
}
```

**Comment by alexsoble** [comment]
@benmolin Thanks for raising this! Unless I'm misreading something, there's a total contradiction between the IL guide on this topic and the [federal guide](https://www.fns.usda.gov/snap/eligibility/elderly-disabled-special-rules#What%20are%20the%20SNAP%20income%20limits?), which says:

"Most SNAP households must meet both the gross and net income limits or they are not eligible for SNAP and cannot receive benefits. However, a household with an elderly or disabled person only has to meet the net income test."

I think working with a SNAP expert or advocate on the ground in IL would be the best way to resolve this and better understand the situation. I believe in a meeting with our contact in Philadelphia, we heard that PA does have a 200% limit for households with an elderly or disabled member, which points to the need for a `gross_income_limit_factor_elderly_or_disabled` key like you suggest!

**Comment by benmolin** [comment]
@alexsoble Great find with that federal guide. I agree I think getting an answer from an expert is the path forward here... I'll come back to this issue when I figure it out. I think Illinois is a good example because they are very clear about the 200% limit on the IL DHS website -- yes PA has the same in my understanding but they don't make it as clear in their official viewer-friendly materials. 

I believe I am misunderstanding something as in the [PA State Handbook](http://services.dpw.state.pa.us/oimpolicymanuals/snap/512_Categorical_Eligibility/512_1_General_Policy.htm) they mention both the "NO GROSS INCOME TEST" and the 200% limit.

> REMINDER: There is no gross income test applied in the system for elderly or disabled households. Elderly or disabled households with income exceeding 200 percent of the FPIGs (though not categorically eligible) may remain potentially eligible if they pass the net test. Many households may qualify for the minimum benefit.

**Comment by benmolin** [comment]
@alexsoble I think I got it.

If you are senior_or_elderly household, you first see if you pass the 200% gross income test. 

- If you pass, there is no asset limit and you are "categorically eligible". 
- If you don't pass, then you can still qualify if you make the $3500 asset limit.

Put another way -- senior household have to pass the net income test and either of the gross income test or the $3500 asset test.

From [Illinois guide](https://www.dhs.state.il.us/page.aspx?item=13635): 

> - Categorically eligible qualifying member units with gross monthly income at 200% FPL or below are eligible for SNAP benefits if they qualify for a benefit amount.  A net income test and an asset test is not required.
> - A qualifying member unit whose gross monthly income exceeds 200% FPL is not categorically eligible and must meet the net income eligibility test and the asset test.

This is consistent with footnote 2 in the [BBCE](https://fns-prod.azureedge.net/sites/default/files/resource-files/BBCEStatesChart%28May2020%29.pdf) guide:

> In these States, households with seniors or people with disabilities and gross income under 200 percent of poverty
do not face an asset limit. Those over 200 percent of poverty are not categorically eligible and do face a $3,500 asset
limit.

**Comment by benmolin** [comment]
Update: My initial issue / statement "Illinois does have a gross income test for elderly_or_disabled" isn't quite true as answered in the comment directly above. There is no strict gross income test, just a limit that dictates whether you have to pass an asset test. This situation is being resolved [here](https://github.com/18F/snap-js-api-prototype/issues/35), and I don't believe the initial code I suggested in this issue is correct.
